### ISSUE TITLE
Fails to build from source on Debian unstable (amd64)

### ISSUE THREAD

**Issue by ryanakca** [gophernicus/gophernicus#80] opened 2020-08-03 14:23 UTC
gophernicus currently fails to build from source on Debian stable:

```
cc -Wl,-z,relro -Wl,-z,now  gophernicus.o file.o menu.o string.o platform.o session.o options.o -lwrap -o gophernicus
/usr/bin/ld: file.o:/usr/include/tcpd.h:115: multiple definition of `deny_severity'; gophernicus.o:/usr/include/tcpd.h:115: first defined here
/usr/bin/ld: file.o:/usr/include/tcpd.h:114: multiple definition of `allow_severity'; gophernicus.o:/usr/include/tcpd.h:114: first defined here
/usr/bin/ld: menu.o:/usr/include/tcpd.h:115: multiple definition of `deny_severity'; gophernicus.o:/usr/include/tcpd.h:115: first defined here
/usr/bin/ld: menu.o:/usr/include/tcpd.h:114: multiple definition of `allow_severity'; gophernicus.o:/usr/include/tcpd.h:114: first defined here
/usr/bin/ld: string.o:/usr/include/tcpd.h:115: multiple definition of `deny_severity'; gophernicus.o:/usr/include/tcpd.h:115: first defined here
/usr/bin/ld: string.o:/usr/include/tcpd.h:114: multiple definition of `allow_severity'; gophernicus.o:/usr/include/tcpd.h:114: first defined here
/usr/bin/ld: platform.o:/usr/include/tcpd.h:115: multiple definition of `deny_severity'; gophernicus.o:/usr/include/tcpd.h:115: first defined here
/usr/bin/ld: platform.o:/usr/include/tcpd.h:114: multiple definition of `allow_severity'; gophernicus.o:/usr/include/tcpd.h:114: first defined here
/usr/bin/ld: session.o:/usr/include/tcpd.h:115: multiple definition of `deny_severity'; gophernicus.o:/usr/include/tcpd.h:115: first defined here
/usr/bin/ld: session.o:/usr/include/tcpd.h:114: multiple definition of `allow_severity'; gophernicus.o:/usr/include/tcpd.h:114: first defined here
/usr/bin/ld: options.o:/usr/include/tcpd.h:115: multiple definition of `deny_severity'; gophernicus.o:/usr/include/tcpd.h:115: first defined here
/usr/bin/ld: options.o:/usr/include/tcpd.h:114: multiple definition of `allow_severity'; gophernicus.o:/usr/include/tcpd.h:114: first defined here
collect2: error: ld returned 1 exit status
```

This is [Debian bug #966853](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=966853). The full build log is available from: http://qa-logs.debian.net/2020/08/02/gophernicus_3.0.1-1_unstable.log

**Comment by augfab** [comment] 2020-08-04 12:05
I see it failed yesterday as well: http://qa-logs.debian.net/2020/08/03/gophernicus_3.0.1-1_unstable.log

Couple questions:

* What commit was built? Is it upstream [`master`](https://github.com/gophernicus/gophernicus/commit/c74cfb33b6b4c1122c61c7a68d6a3808985d1a25) or [salsa's `debian/sid`](https://salsa.debian.org/debian/gophernicus/-/commit/b7b0e040ce99a3ffca50a1b4cee8fe925df9d712)? Something else?
* I can't reproduce locally (Ubuntu 20.04), with either of the mentioned commits. I have an idea for a fix but I can't test if it works.
 Is there a way to test changes manually with Debian's QA?
* Would you like to upstream the changes you made in `gophernicus`'s Debian packaging scripts?

**Comment by fosslinux** [comment] 2020-08-04 23:32
I think the better option is to remove the Debian packaging scripts from the repo entirely.

This is the route most other packages follow, the Debian packaging scripts were only kept as an option for people to build their own packages. If they still want to do that they should do it the official Debian way. I think I will remove the scripts with 3.1.

**Comment by ryanakca** [comment] 2020-08-04 23:42
The Debian package builds the 3.0.1 release (your v3.0.1 tag). It (plus Debian-specific packaging changes) can be found on debian/sid branch on salsa.

If you want to test locally on Ubuntu, you should be able to use the "schroot" tool to create a Debian unstable chroot on Ubuntu without too much trouble. Alternatively, you're welcome to send me the patch and I can test it for you.

And fosslinux is right, the best option is to remove the Debian packaging scripts from the repo entirely.

**Comment by fosslinux** [comment] 2020-08-05 07:12
This bug is already fixed as of the current commit, very recently. The patch is rather large, however, and I plan to release 3.1 soon.

I am unfamiliar with Debian's building process. If it needs to be built sooner rather than later I can release a hotfix 3.0.2.

**Comment by ryanakca** [comment] 2020-08-06 16:10
Thanks, and sorry: I should have done the legwork of checking if it had been fixed in Git.

There is no particular rush. The archive software will automatically remove the package from the "testing" distribution (which becomes the "stable" distribution), probably in a month or so. That said, the stable freeze isn't scheduled to happen until early 2021, so we have time yet to get a fix uploaded if we're to get the package included in the next stable release.

**Comment by ryanakca** [comment] 2020-11-29 15:49
As a heads up, Debian will enter a freeze on January 12, 2021. That means that for gophernicus to be included in the next Debian release, I need to upload it a week or more before that.

**Comment by fosslinux** [comment] 2020-11-29 22:48
Thanks for the notice. I will have a release by mid-december.

**Closed** 2020-12-23 00:20 UTC
